### ISSUE TITLE
Publish hrval image to public registry

### ISSUE THREAD

**Issue by wwentland** [stefanprodan/hrval-action#10]
It would be great if an official hrval image could be made available on a public image registry such as Quay or Docker Hub.

Doing so would allow users to utilise it without either having to maintain an image themselves or, alternatively, having to bootstrap it during the pipeline run as documented in the README:

```
      - run:
          name: Install hrval
          command: |
            curl -sL https://raw.githubusercontent.com/stefanprodan/hrval-action/master/src/deps.sh | sudo bash
            sudo curl -sL https://raw.githubusercontent.com/stefanprodan/hrval-action/master/src/hrval.sh \
              -o /usr/local/bin/hrval.sh && sudo chmod +x /usr/local/bin/hrval.sh
            sudo curl -sL https://raw.githubusercontent.com/stefanprodan/hrval-action/master/src/hrval-all.sh \
              -o /usr/local/bin/hrval && sudo chmod +x /usr/local/bin/hrval
```

Thank you!

**Comment by stefanprodan** [comment]
@babilen5 the image is on Docker Hub at `stefanprodan/hrval:v2.4.0`
