### ISSUE TITLE
support authenticated chart repositories

### ISSUE THREAD

**Issue by omerlh** [stefanprodan/hrval-action#24]
Currently, there is no way to test HelmRelease when the release is pointing to an authenticated cart repository. This is because the `helm repo add` line, that is failed if the repo is authenticated.

**Comment by stefanprodan** [comment]
You need to provide a GitHub token for private repos as described here https://github.com/stefanprodan/hrval-action#usage-with-private-charts-repositories

**Comment by omerlh** [comment]
The repo is stored on Azure ACR - using GitHub token will not help in this case...

**Comment by omerlh** [comment]
I solved it by running `helm repo add` myself just before running the tests. There is an error when hrval trying to add the repo, but it does not fail the tests.

**Comment by stefanprodan** [comment]
I think we can improve this and run `helm repo add` only if the repo URL is not in `repositories.yaml`. I also think we should add a private repo example to the docs.
